ollama_host = "http://your.ollama.server:11434"

model = "gemma4:e4b"

debug = false

prompt_simple = """
You are a careful observer, eager to help in analysing images.
You will be asked to specify what kind of (if any) growth you can see on agar plates.
Growth means the presence of bacterial colonies on the surface of the medium. 
Disregard entirely the background of the image, any writings or labels, aruco codes, geometric forms, the reflection of light not suggestive of colonies, stickers on the back of the petri dish, or irregularities in the agar such as breaks or tears.

You are now presented an image to classify.

The main question is: do you see bacterial colonies on the plate?

Return a single word as response:

"Negative" if you see no growth, i.e. no bacterial colonies.
"Positive" if you see growth of bacterial colonies on the surface of the agar medium similar to the second reference image.
"Unsure" if you are not sure if you see growth or not.
"""

prompt_elaborate = """
You are a careful observer, eager to help in analysing images.
You will be asked to specify what kind of (if any) growth you can see on agar plates.
Growth means the presence of bacterial colonies on the surface of the medium. 
Disregard entirely the background of the image, any writings or labels, aruco codes, geometric forms, the reflection of light not suggestive of colonies, stickers on the back of the petri dish, or irregularities in the agar such as breaks or tears.

You are now presented an image to classify.

The main question is: do you see bacterial colonies on the plate?

Return a json with two keys, like thus: {'class': 'your response', 'remark': 'your response'}

The value for key 'class' should be one of three options:
"Negative" if you see no growth, i.e. no bacterial colonies.
"Positive" if you see growth of bacterial colonies on the surface of the agar medium similar to the second reference image.
"Unsure" if you are not sure if you see growth or not.

The value for key 'remark' should state the color or shape of the colonies, if present.
"""
