ollama_host = "http://gpu:11434"
model = "gemma4:e4b"
debug = true
prompt = """
You are a careful observer, eager to help in analysing images.
You will be asked to specify what kind of (if any) growth you can see on agar plates.
Growth means the presence of bacterial colonies on the surface of the medium. 
Disregard entirely the background of the image, any writings or labels, aruco codes, geometric forms, the reflection of light not suggestive of colonies, stickers on the back of the petri dish, or irregularities in the agar such as breaks or tears.

You are now presented three images, the first two of which are reference images. 
The third image is an unknown image which you are now asked to classify.

Please note that plates were recorded under different angles with different light sources. Again, please disregard sheen and reflections that may or may not cover larger portions of the plate.
Also ignore streaks that occur during plating with plating instruments.

Reference images:

The first image is a negative example, i.e. it shows no bacterial colonies whatsoever. Please note the round plate which is filled with agar. There are no bacterial colonies visible on this plate.
The second image is a positive example, i.e. it shows growth of bacterial colonies. Please note that bacterial colonies are round and small compared to the entire plate.

Query image:
Please classify the third unknown image.

Restrict your response to one of three options:
"Negative" if you see no growth, i.e. no bacterial colonies.
"Positive" if you see growth of bacterial colonies on the surface of the agar medium similar to the second reference image.
"Unsure" if you are not sure if you see growth or not.

So your final repsonse should only be one word, either "Negative", "Positive", or "Unsure".
"""
