ollama_host = "http://gpu:11434"
model = "qwen3.5:4b"
debug = true
prompt = """
You are a careful observer, eager to help in analysing images.
You will be asked to specify what kind of (if any) growth you can see on agar plates.
Growth means the presence of bacterial colonies on the surface of the medium. 
Disregard entirely the background of the image, any writings or labels, aruco codes, geometric forms, the reflection of light, stickers on the back of the petri dish, or irregularities in the agar such as breaks or tears.

You are now presented four images, the first three of which are reference images. 
The fourth image is an unknown image which you are now asked to classify.

Reference images:

The first image is a negative example, i.e. it shows no bacterial colonies whatsoever.
The second image is a positive example, i.e. it shows growth of reddish colonies.
The third image is also a positive example, but it shows growth of greenish colonies.

Query image:
Please classify the fourth unknown image.

Restrict your response to one of five options:
"Negative" if you see no growth, i.e. no bacterial colonies.
"Red" if you see growth of reddish bacterial colonies on the surface of the agar medium similar to the second reference image.
"Green" if you see growth of greenish bacterial colonies similar to the third reference image.
"Other" if you see growth that is either a mix of colonies or of a color unrelated to the second or third reference images.
"Unsure" if you are not sure if you see growth or not.

So your final repsonse should only be one word, either "Negative", "Red", "Green", "Other", or "Unsure".
"""
